### ISSUE TITLE
获取地理位置时候出错

### ISSUE THREAD

**Issue by andyxxchen** [Eanya-Tonic/HDU-Health_checkin#2]
我用的杭州节点的阿里云轻量服务器，chrome和chromedrive版本都是Google Chrome 99.0.4844.51。每次到最后点击确认按钮时候，总会报授权地理位置时候出错。大佬请问是什么原因

**Comment by Eanya-Tonic** [comment]
尝试增长下sleep的时间试试，虽然使用了模拟定位但是有的时候还是需要等待一会儿才能获取到位置

**Comment by andyxxchen** [comment]
> 尝试增长下sleep的时间试试，虽然使用了模拟定位但是有的时候还是需要等待一会儿才能获取到位置

刚刚试了，还是报这个错误
<img width="570" alt="image" src="https://user-images.githubusercontent.com/69415007/164986162-9a7062d3-7aaf-415e-a441-e06c5de33340.png">

**Comment by andyxxchen** [comment]
试了下，其他版本的chrome和chromedrive也是报这个错误

**Comment by Eanya-Tonic** [comment]
![image](https://user-images.githubusercontent.com/74545593/165010139-c8b7cdab-6b64-45ef-b23b-490612a0c438.png)
更新了一下仓库，加入了选择疫苗选项的功能
加入疫苗选择后，我这里已经实现了打卡，并在今天（4.25）打卡成功
你可以尝试把代码先放在本地机器，取消无头参数执行一下，观察Chrome和网页的相应情况，看看是运行到哪步出现了明显的问题
此外，本段代码在前段时间突然无法正常打卡，会出现未知错误（但会提示打卡成功），但今天测试又已经可以正常使用；专门咨询了杭电助手的同学无果，目前判断为玄学原因，请谨慎使用

**Comment by andyxxchen** [comment]
> 

感谢作者大大，我也已经成功运行了
先试一段时间，如果出现你所说的未知错误打卡成功，是否可以加入webdriver刷新的和再用chromedrive查找网页上的指定元素是否是```已打卡```样式
